---
- name: Deploy to Tomcat
  hosts: web
  become: true
  become_user: root

  tasks:

    - name: Copy WAR file to Tomcat
      copy:
        src: /var/lib/jenkins/workspace/MavenAnsible/target/MavenAnsible.war
        dest: /opt/tomcat/webapps/MavenAnsible.war
        owner: root
        group: root
        mode: '0644'

    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted
